### ISSUE TITLE
Building Initial HTML

### ISSUE THREAD

**Issue by cmarshall13** [trippjoe/bandspot#6]
**User Story**
As a music enthusiast
I want an app to connect to my spotify
so that I can see my top artists and find concerts/events going on near me

*Acceptance

- [x] Add title to header
- [x] Add container to hold content
- [x] Add dynamic spotify sign-in button
- [x] Add footer

**Comment by brentocracy** [comment]
@cmarshall13, `lines 78-82` in the HTML file should be taken out - the scripts are called twice.

Also, it would be fantastic to add the `import script` for Moment.js. The code would be:

`<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script> `
